site_name: Bayesian Optimization as a Coverage Tool for LLM
theme:
  name: material
  logo: assets/logo.png
  favicon: assets/logo.png
  icon:
    repo: material/github
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs
docs_dir: mkdocs
edit_uri: ""
site_url: https://bocoel.pages.dev
repo_name: rentruewang/bocoel
repo_url: https://github.com/rentruewang/bocoel
plugins:
  - search
  - social
  - mkdocstrings
  - git-revision-date
  - git-revision-date-localized
  - git-committers:
      repository: rentruewang/bocoel
      branch: main
nav:
  - Home:
    - README: README.md
  - Contributing:
    - CONTRIBUTING.md
    - CODE_OF_CONDUCT.md
  - Reference:
    - CHANGELOG.md
