[tool.poetry]
name = "bocoel"
version = "0.0.0"
description = "Bayesian Optimization as a Coverage Tool for Evaluating Large Language Models"
authors = ["RenChu Wang <patrick1031wang@gmail.com>"]
license = "Apache 2.0"
readme = "README.md"


[tool.poetry.dependencies]
datasets = "^2.16.1"
fire = "^0.5.0"
numpy = "^1.26.2"
pandas = "^2.1.4"
python = "^3.10"
pyyaml = "^6.0.1"
scipy = "^1.11.4"
torch = "^2.1.2"
typing-extensions = "^4.9.0"
ujson = "^5.9.0"


[tool.poetry.extras]
visual = [
    "dash>=2.14.2",
    "flask>=3.0.0",
    "hiplot>=0.1.33",
    "plotly>=5.18.0",
]

[tool.poetry.group.dev.dependencies]
autoflake = "^2.2.1"
black = "^23.12.0"
ipython = "^8.18.1"
isort = "^5.13.2"
mypy = "^1.8.0"
pytest = "^7.4.3"
pytest-xdist = "^3.5.0"


[tool.poetry.group.bo]
optional = true

[tool.poetry.group.bo.dependencies]
ax-platform = "^0.3.6"
botorch = "^0.9.5"
gpytorch = "^1.11"
scikit-learn = "^1.3.2"

[tool.poetry.group.index]
optional = true

[tool.poetry.group.index.dependencies]
faiss-cpu = "^1.7.4"
hnswlib = "^0.8.0"

[tool.poetry.group.llm]
optional = true

[tool.poetry.group.llm.dependencies]
sentence-transformers = "^2.2.2"
transformers = "^4.36.2"
vllm = "^0.2.7"

[tool.poetry.group.metrics]
optional = true

[tool.poetry.group.metrics.dependencies]
rouge = "^1.0.1"
nltk = "^3.8.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"
