[project]
name = "bocoel"
version = "0.0.1"
description = "Bayesian Optimization as a Coverage Tool for Evaluating Large Language Models"
authors = [
    {name = "RenChu Wang", email = "patrick1031wang@gmail.com"},
]
dependencies = [
    "ax-platform>=0.3.6",
    "botorch>=0.9.5",
    "datasets>=2.16.1",
    "gpytorch>=1.11",
    "fire>=0.5.0",
    "linear-operator>=0.5.1",
    "nltk>=3.8.1",
    "numba>=0.58.1",
    "numpy>=1.26.3",
    "pandas>=2.1.4",
    "pyyaml>=6.0.1",
    "rich>=13.7.0",
    "rouge>=1.0.1",
    "rouge-score>=0.1.2",
    "sacrebleu>=2.4.0",
    "scikit-learn>=1.3.2",
    "scipy>=1.11.4",
    "sentence-transformers>=2.2.2",
    "torch>=2.1.2",
    "transformers>=4.36.2",
    "typing-extensions>=4.9.0",
    "ujson>=5.9.0",
]
requires-python = ">=3.10,<3.11"
readme = "README.md"
license = {text = "Apache-2.0"}

[project.optional-dependencies]
visual = [
    "dash>=2.14.2",
    "flask>=3.0.0",
    "hiplot>=0.1.33",
    "plotly>=5.18.0",
]
faiss = [
    "faiss-cpu>=1.7.4",
]
hnswlib = [
    "hnswlib>=0.8.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"


[tool.pdm]
package-type = "library"

[tool.pdm.dev-dependencies]
format = [
    "autoflake>=2.2.1",
    "black>=23.12.1",
    "isort>=5.13.2",
]
test = [
    "coverage>=7.4.0",
    "pytest>=7.4.4",
    "pytest-cov>=4.1.0",
    "pytest-xdist>=3.5.0",
]
type = [
    "mypy>=1.8.0",
]
