title: Bocoel
author: RenChu Wang
copyright: '2024'
logo: assets/logo.svg
icon: assets/logo.svg

exclude_patterns: [_build]
only_build_toc_files: true

repository:
  url: https://github.com/rentruewang/bocoel

html:
  use_repository_button: true

execute:
  execute_notebooks: force

sphinx:
  extra_extensions: [
    sphinx.ext.napoleon,
    sphinx.ext.intersphinx,
    sphinx.ext.autodoc,
    sphinxcontrib.mermaid,
  ]
  myst_fence_as_directive: [mermaid]
  config:
    intersphinx_mapping:
      python: ['https://docs.python.org/3', null]
